-- MySQL Script generated by MySQL Workbench
-- 04/27/17 23:22:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bavuta_example
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bavuta_example
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bavuta_example` DEFAULT CHARACTER SET utf8 ;
USE `bavuta_example` ;

-- -----------------------------------------------------
-- Table `bavuta_example`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bavuta_example`.`ROLES` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(255) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `ROLE_UNIQUE` (`ROLE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bavuta_example`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bavuta_example`.`USERS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `ROLE_ID` INT UNSIGNED NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  INDEX `fk_USERS_ROLES_idx` (`ROLE_ID` ASC),
  CONSTRAINT `fk_USERS_ROLES`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `bavuta_example`.`ROLES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
